---

- hosts: mongo
  remote_user: root
  tasks:
    - name: Add MongoDB apt key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present

    - name: Add MongoDB repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse

    - name: Install MongoDB
      apt:
        name: mongodb-org
        update_cache: yes

    - name: Start service MongoDB
      service:
        name: mongod
        state: started

    - name: Config MongoDB
      template:
        src: mongod.conf.j2
        dest: /etc/mongod.conf

    - name: Restart service MongoDB
      service:
        name: mongod
        state: restarted

- hosts: mongo-config
  remote_user: root
  tasks:
    - name: Config MongoDB
      template:
        src: mongod-config.conf.j2
        dest: /etc/mongod.conf

    - name: Initialize rs
      template:
        src: mongo-config.js.j2
        dest: /tmp/mongo-config.js

    - name: Run rs
      shell: /usr/bin/mongo < /tmp/mongo-config.js

    - name: Restart service MongoDB
      service:
        name: mongod
        state: restarted

- hosts: mongo-shard
  remote_user: root
  tasks:
    - name: Config MongoDB
      template:
        src: mongod-shard.conf.j2
        dest: /etc/mongod.conf

    - name: Initialize rs
      template:
        src: mongo-shard.js.j2
        dest: /tmp/mongo-shard.js

    - name: Run rs
      shell: /usr/bin/mongo < /tmp/mongo-shard.js

    - name: Restart service MongoDB
      service:
        name: mongod
        state: restarted

- hosts: mongo-router
  remote_user: root
  tasks:
    - name: Config MongoDB
      template:
        src: mongod-router.conf.j2
        dest: /etc/mongod.conf

    - name: Edit Mongos service
      lineinfile:
        path: /lib/systemd/system/mongod.service
        regexp: '^ExecStart=/usr/bin/mongod --config /etc/mongod.conf'
        line: 'ExecStart=/usr/bin/mongos --config /etc/mongod.conf'

    - name: Initialize rs
      template:
        src: mongo-router.js.j2
        dest: /tmp/mongo-router.js

    - name: Run rs
      shell: /usr/bin/mongo < /tmp/mongo-router.js

    - name: Restart service MongoDB
      service:
        name: mongod
        state: restarted
